config/routes.rb
Stepoutside::Application.routes.draw do
  devise_for :users
  root  'stepoutside#home'
  match '/about',   to: 'stepoutside#about',   via: 'get'
  match '/forecast',   to: 'stepoutside#forecast',   via: 'get'
  match '/time',   to: 'stepoutside#time',   via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stepoutside_controller.rb
class StepoutsideController < ApplicationController
  def home
  end

  def about
  end

  def forecast
  end

  def time
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "StepOutside"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/stepoutside_helper.rb
module StepoutsideHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to (image_tag "sologowhite.png", width: "150px"), root_path, id: "logo" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",     root_path %></li>
            <li><%= link_to "Forecast", forecast_path %></li>
            <li><%= link_to "Time",     time_path %></li>
            <li><%= link_to "About",    about_path %></li>
            <%= render 'layouts/user_widget' %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
  </ul>
</li>
<% else %>
  <li><%= link_to 'Login/Signup', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?sensor=false' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
<div id="infos">
  <div id="notice" class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
    <p class="notice"><%= notice %></p>
  </div>
  <div id="alert" class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
    <p class="alert"><%= alert %></p>
  </div>
</div>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div id="landing">
  <h1>StepOutside</h1>
  <h3 class="text-center">A time and weather web app</h3>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6" id="searchdiv">
    <span class="glyphicon glyphicon-search" id="go"></span>
     <input type="search" name="location" id="search" placeholder="Search for any city..." autocomplete="off" autofocus="autofocus">
  </div>
</div>
<div class="info text-center"><p><small><em>Just begin typing to select your city</em></small></p></div>
<div class="row" id="main">

  <div class="col-md-5 text-right card">
    <h1 class="text-left">Weather</h1>
      <div class="col-sm-6 text-center hidden-xs">
         <%= image_tag "icons/na.png", :id => "weather-img", :width => "75%" %>
      </div>
      <div class="text-left clearfix">
              Summary: <strong><span id="summary"></span></strong>
      <br>    Temperature: <strong><span id="temperature"></span></strong>
      <br>    Feels like: <strong><span id="apptemperature"></span></strong>
      <br>    Chance of Rain: <strong><span id="rainchance"></span></strong>
      <br>    Max Temperature: <strong><span id="maxtemperature"></span></strong>
      <br>    Min Temperature: <strong><span id="mintemperature"></span></strong>
      <br>    Wind Speed: <strong><span id="windspeed"></span></strong>
      <br>    Cloud Cover: <strong><span id="cloudcover"></span></strong>
      <br>    Humidity: <strong><span id="humidity"></span></strong>
      </div>
      <a href="#" id="see-more">More</a>
      <div class="col-md-12 text-left" id="more">
        <hr>
        <h4>More info</h4>
              Sunrise Time: <strong><span id="sunrise"></span></strong>
      <br>    Sunset Time: <strong><span id="sunset"></span></strong>
      </div>
  </div>

  <div class="col-md-5 text-left card">
    <h1 class="text-left">Time</h1>
    <div class="row">
      <div class="col-sm-6">
              Current Time: <strong><span id="currenttime"></span></strong>
      <br>    Time Zone: <strong><span id="timezone"></span></strong>
      <br>    Offset: <strong><span id="offset"></span></strong>
      <br>    Latitude: <strong><span id="latitude"></span></strong>
      <br>    Longitude: <strong><span id="longitude"></span></strong>
      </div>
      <div class="col-sm-6">
              <h3>Local</h3>
              Local Time: <strong><span id="localtime"></span></strong>
      <br>    Time Zone: <strong><span id="localtimezone"></span></strong>
      </div>
    </div>
      <br>
      <div class="row">
      <div class="col-md-12">
        <hr>
        <h3>Location</h3>
        <strong><span id="location"> &nbsp; </span></strong>
      </div>
    </div>
  </div>

</div>

app/views/stepoutside/about.html.erb
<% provide(:title, 'About') %>
<div class="row">
	<div class="col-md-offset-2 col-md-8">
<div class="card">
	<div class="row">
	<div class="col-xs-offset-1 col-xs-10">
	<h1>About</h1>
	<br>
	<p>
		StepOutside is a web app built using the Ruby on Rails framework. 
		You can search for any city in the world to get its get current weather 
		conditions, timezone, current time and weekly forecast among other things.
	</p>
	<p>
		The ability to search for any location in the word is provided by 
		<%= link_to "jquery-addresspicker", "https://github.com/sgruhier/jquery-addresspicker/" %> 
		by <%= link_to "sgruhier", "https://github.com/sgruhier/" %> 
		which uses the <%= link_to "Google Maps API", "https://developers.google.com/maps/" %>.
		<br>
		Weather forecasts are made available using the <%= link_to "forecast.io", "forecast.io/" %> 
		<%= link_to "API", "https://developer.forecast.io/" %>.
	</p>
	<p>
		The source code of this web app is freely available to all and can be found 
		<%= link_to "here", "https://github.com/pbaisla/stepoutside" %>.
	</p>
	<br>
	</div>
	</div>
	</div>
	</div>
</div>
<%= image_tag "about.jpg", :class => "bgimage" %>

app/views/stepoutside/forecast.html.erb
<% provide(:title, 'Forecast') %>
<div id="landing">
  <div class="row"><div class="col-xs-offset-3"><%= image_tag "sologo.png", :id => "sologo", :width => "70%" %></div></div>
  <h3 class="text-center">Weekly forecast</h3>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6" id="searchdiv">
    <span class="glyphicon glyphicon-search" id="go"></span>
     <input type="search" name="location" class="form-control" id="forecastsearch" placeholder="Search for any city..." autocomplete="off" autofocus="autofocus">
  </div>
  <div class="col-xs-11 col-sm-5 fcard" id="locationcard">
    Location
    <strong><span id="location"> &nbsp; </span></strong>
  </div>
</div>
<div class="info text-center"><p><small><em>Just begin typing to select your city</em></small></p></div>
<div class="row text-center">
  <div class="col-sm-offset-5 col-sm-2 hidden-xs">
    <%= image_tag "spinner.gif", :id => "spinner", :width => "100px" %>
  </div>
</div>

<div class="row" id="main">
<% for i in 0..7 %>
  <div class="col-md-5 text-right fcard" id="card<%= i %>">
    <div class="row">
    <h1 class="text-left col-sm-8"><span id="day<%= i %>"></span></h1>
    <div class="text-right col-sm-4"><button type="button" class="btn tchange"><span class="badge celcius">°C</span> <span class="fahrenheit">°F</span></button></div>
    </div>
      <div class="col-sm-6 text-center hidden-xs">
         <%= image_tag "icons/na.png", :id => "weather-img" + i.to_s, :class => "weather-img", :width => "75%" %>
      </div>
      <div class="text-left clearfix">
              Sunrise Time: <strong><span id="sunrise<%= i %>"></span></strong>
      <br>    Sunset Time: <strong><span id="sunset<%= i %>"></span></strong>
      <br>    Max Temperature: <strong><span id="maxtemperature<%= i %>"></span></strong>
      <br>    Min Temperature: <strong><span id="mintemperature<%= i %>"></span></strong>
      <br>    Humidity: <strong><span id="humidity<%= i %>"></span></strong>
      <br>    Chance of Rain: <strong><span id="rainchance<%= i %>"></span></strong>
      </div>
    <div class="row">
      <div class="col-xs-12 text-left">
        <br>
        Summary: <strong><span id="summary<%= i %>"></span></strong>
      </div>
    </div>
  </div>

<% end -%>
<%= image_tag "arrow.png", :id => "arrow", :class => "hidden-xs" %>
</div>
<%= image_tag "weathe.jpg", :id => "bgimage", :class => "bgimage" %>

app/views/stepoutside/home.html.erb
<div id="landing">
  <div class="row"><div class="col-xs-offset-3"><%= image_tag "sologo.png", :id => "sologo", :width => "70%" %></div></div>
  <h3 class="text-center">A time and weather web app</h3>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6" id="searchdiv">
    <span class="glyphicon glyphicon-search" id="go"></span>
     <input type="search" name="location" class="form-control" id="search" placeholder="Search for any city..." autocomplete="off" autofocus="autofocus">
  </div>
</div>
<div class="info text-center"><p><small><em>Just begin typing to select your city</em></small></p></div>
<div class="row text-center">
  <div class="col-sm-offset-5 col-sm-2 hidden-xs">
    <%= image_tag "spinner.gif", :id => "spinner", :width => "100px" %>
  </div>
</div>
<div class="row" id="main">

  <div class="col-md-5 text-right card">
  <div class="row">  
    <h1 class="text-left col-sm-8">Weather</h1>
    <div class="text-right col-sm-4"><button type="button" class="btn tchange"><span class="badge celcius">°C</span> <span class="fahrenheit">°F</span></button></div>
    </div>
      <div class="col-sm-6 text-center hidden-xs">
         <%= image_tag "icons/na.png", :id => "weather-img", :width => "75%" %>
      </div>
      <div class="text-left clearfix">
              Summary: <strong><span id="summary"></span></strong>
      <br>    Temperature: <strong><span id="temperature"></span></strong>
      <br>    Feels like: <strong><span id="apptemperature"></span></strong>
      <br>    Max Temperature: <strong><span id="maxtemperature"></span></strong>
      <br>    Min Temperature: <strong><span id="mintemperature"></span></strong>
      <br>    Wind Speed: <strong><span id="windspeed"></span></strong>
      <br>    Chance of Rain: <strong><span id="rainchance"></span></strong>
      <br>    Cloud Cover: <strong><span id="cloudcover"></span></strong>
      <br>    Humidity: <strong><span id="humidity"></span></strong>
      </div>
      <div class="text-right"><a href="#" id="see-more">More</a></div>
      <div class="text-left"><%= link_to "See weekly forecast", forecast_path, :id => "forecastlink" %></div>
      <div class="col-md-12 text-left" id="more">
        <hr>
      <div class="col-md-12 text-left">
        <h4>More info</h4>
              Sunrise Time: <strong><span id="sunrise"></span></strong>
      <br>    Sunset Time: <strong><span id="sunset"></span></strong>
      </div>
      </div>
  </div>

  <div class="col-md-5 text-left card">
    <h1 class="text-left">Time</h1>
    <div class="row">
      <div class="col-sm-6">
              Current Time: <strong><span id="currenttime"></span></strong>
      <br>    Time Zone: <strong><span id="timezone"></span></strong>
      <br>    Offset: <strong><span id="offset"></span></strong>
      <br>    Latitude: <strong><span id="latitude"></span></strong>
      <br>    Longitude: <strong><span id="longitude"></span></strong>
      </div>
      <div class="col-sm-6">
              <h3>Local</h3>
              Local Time: <strong><span id="localtime"></span></strong>
      <br>    Time Zone: <strong><span id="localtimezone"></span></strong>
      </div>
    </div>
      <br>
      <div class="row">
      <div class="col-md-12">
        <hr>
        <h3>Location</h3>
        <strong><span id="location"> &nbsp; </span></strong>
      </div>
    </div>
  </div>

</div>
<%= image_tag "background1.jpg", :id => "bgimage", :class => "bgimage" %>

app/views/stepoutside/time.html.erb
<% provide(:title, 'Time') %>
<div id="landing">
  <div class="row"><div class="col-xs-offset-3"><%= image_tag "sologo.png", :id => "sologo", :width => "70%" %></div></div>
  <h3 class="text-center">World Time</h3>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6" id="searchdiv">
    <span class="glyphicon glyphicon-search" id="go"></span>
     <input type="search" name="location" class="form-control" id="search" placeholder="Search for any city..." autocomplete="off" autofocus="autofocus">
  </div>
</div>
<div class="info text-center"><p><small><em>Just begin typing to select your city</em></small></p></div>
<div class="row text-center">
  <div class="col-sm-offset-5 col-sm-2 hidden-xs">
    <%= image_tag "spinner.gif", :id => "spinner", :width => "100px" %>
  </div>
</div>
<div class="row" id="main">

  <div class="col-md-5 text-left card">
    <h1 class="text-left">Time</h1>
    <div class="row">
      <div class="col-sm-12">
      <div class="time"><strong><span id="currenttime"></span></strong></div>
      </div>
      <div class="col-sm-6">
      <br>    Time Zone: <strong><span id="timezone"></span></strong>
      <br>    Offset: <strong><span id="offset"></span></strong>
      </div>
      <div class="col-sm-6">
      <br>    Latitude: <strong><span id="latitude"></span></strong>
      <br>    Longitude: <strong><span id="longitude"></span></strong>
      </div>
    </div>
      <br>
  </div>

  <div class="col-md-5 text-left card">
    <h1 class="text-left">Local Time</h1>
    <div class="row">
      <div class="col-sm-12">
      <div class="time"><strong><span id="localtime"></span></strong></div>
      </div>
    </div>
      <br>
  </div>
  </div>

</div>
<%= image_tag "time.jpg", :class => "bgimage" %>